#!/usr/bin/env Rscript
# WS1 audit-J: cohort-wide multiple-testing control across ALL inferential families, so no claim
# rests on cherry-picking the best result across the several analyses run. Consolidates the raw
# bootstrap p-values from every family, reports each test's within-family BH AND a pooled global BH,
# and re-annotates the primary couplings with the stricter number.
#
# Families (each test = one bootstrap-CI hypothesis):
#   sc_network   28 tumor-level partial-correlation edges   (the coupling DISCOVERY family)
#   transfer     12 directional axis~lever coefficients     (a re-parameterisation of lever-axis edges)
#   bulk_network 28 bulk partial-correlation edges          (a CONFIRMATORY resolution)
# Pooled BH over the union is deliberately conservative (sc/bulk re-test the same pairs, and transfer
# re-expresses lever-axis edges — all positively correlated), so surviving it is a strong statement.
#
# Output: results/couplings/global_fdr.csv ; prints survivor counts; rewrites the couplings block of
# config/joint_priors.yaml with a `global_bh_fdr` field per edge.
# Usage: Rscript phase1_mechanotypes/23_global_fdr.R   (after coupling_core / 19 / 20)
.script_dir <- local({
  cmd <- commandArgs(trailingOnly = FALSE); path <- sub("--file=", "", cmd[grep("--file=", cmd)])
  if (length(path) == 0) return(normalizePath(".", winslash = "/")); dirname(normalizePath(path, winslash = "/"))
})
source(file.path(.script_dir, "utils.R"))

main <- function() {
  cfg <- load_config(); cd <- resolve_path(cfg, "results/couplings")
  scn <- read.csv(file.path(cd, "network_tumorB_partial.csv"))
  tr  <- read.csv(file.path(cd, "transfer.csv"))
  bkn <- read.csv(file.path(cd, "bulk", "network_bulk_partial.csv"))

  fam <- rbind(
    data.frame(family = "sc_network",   test = paste(scn$a, scn$b, sep = "~"), raw_p = scn$boot_p),
    data.frame(family = "transfer",     test = paste(tr$axis, tr$lever, sep = "~"), raw_p = tr$boot_p),
    data.frame(family = "bulk_network", test = paste(bkn$a, bkn$b, sep = "~"), raw_p = bkn$boot_p))
  # within-family BH (recomputed here so the table is self-contained)
  fam$within_family_bh <- ave(fam$raw_p, fam$family, FUN = function(p) p.adjust(p, "BH"))
  # pooled global BH across every test
  fam$global_bh <- p.adjust(fam$raw_p, "BH")
  fam <- fam[order(fam$global_bh, fam$raw_p), ]
  write.csv(fam, file.path(cd, "global_fdr.csv"), row.names = FALSE)

  cat(sprintf("[global-fdr] %d tests across %d families\n", nrow(fam), length(unique(fam$family))))
  for (f in unique(fam$family)) {
    s <- fam[fam$family == f, ]
    cat(sprintf("  %-13s n=%2d  within-BH<0.10: %d   global-BH<0.10: %d\n",
                f, nrow(s), sum(s$within_family_bh < 0.10), sum(s$global_bh < 0.10)))
  }
  cat("\n[primary sc couplings vs both corrections]\n")
  prim <- fam[fam$family == "sc_network", ]
  prim <- prim[order(prim$raw_p), ]
  print(format(head(prim, 6)[, c("test", "raw_p", "within_family_bh", "global_bh")], digits = 2),
        row.names = FALSE)

  # ---- re-annotate joint_priors.yaml couplings with global_bh_fdr -----------------------------
  jp_path <- file.path(cfg$root, "config", "joint_priors.yaml")
  jp <- yaml::read_yaml(jp_path)
  key_g <- setNames(prim$global_bh, prim$test)
  key_g2 <- setNames(prim$global_bh, paste(sub("~.*", "", prim$test), sub(".*~", "", prim$test)))
  for (i in seq_along(jp$couplings$edges)) {
    e <- jp$couplings$edges[[i]]
    g <- key_g[[paste(e$a, e$b, sep = "~")]]
    if (is.null(g)) g <- key_g[[paste(e$b, e$a, sep = "~")]]
    jp$couplings$edges[[i]]$global_bh_fdr <- if (is.null(g)) NA else round(g, 3)
  }
  jp$couplings$global_fdr_note <- paste(
    "bh_fdr is within the 28-edge sc discovery family (primary). global_bh_fdr is BH pooled across",
    nrow(fam), "tests (sc+transfer+bulk) — deliberately conservative; see results/couplings/global_fdr.csv.")
  writeLines(c("# AUTO-GENERATED by 19_bifurcation_transfer.R; couplings re-annotated by 23_global_fdr.R.",
               "# Coupled, bounded prior for the PhysiCell virtual-cohort sweep (see PLAN §1).",
               yaml::as.yaml(jp)), jp_path)
  cat(sprintf("\n[ok] global_fdr.csv + joint_priors.yaml re-annotated (global_bh_fdr per edge)\n"))
}

if (sys.nframe() == 0) main()
